print("hello");
print("good morning")
print("How are you")
print("welcome to python")
print("S")
print("Sh")
print("Sha")
print("Shab")
print("Shabn")
print("Shabna")
print("Shabnam")
name=input("Enter your name :")
print("welcome" +name)
a=input("enter first number")
b=input("enter second number")
S=int(a)+ int(b) 
print("addition")

